import type { University } from "./types";

export const COUNTRIES = [
  "USA",
  "UK",
  "Canada",
  "Australia",
  "Germany",
  "Ireland",
  "New Zealand",
] as const;

export const UNIVERSITIES: University[] = [
  {
    id: "ucb",
    name: "University of California, Berkeley",
    country: "USA",
    city: "Berkeley, California",
    ranking: "Top 5 globally",
    tuition: "$48,000 – $55,000 / year",
    programs: ["Computer Science", "Engineering", "Business", "Data Science"],
    duration: "1–4 years",
    language: "IELTS 7.0 / TOEFL 90",
    visa: "OPT up to 3 years for STEM",
  },
  {
    id: "stanford",
    name: "Stanford University",
    country: "USA",
    city: "Stanford, California",
    ranking: "Top 3 globally",
    tuition: "$52,000 – $58,000 / year",
    programs: ["Computer Science", "Business", "Engineering"],
    duration: "1–4 years",
    language: "IELTS 7.0 / TOEFL 100",
    visa: "OPT up to 3 years for STEM",
  },
  {
    id: "manchester",
    name: "University of Manchester",
    country: "UK",
    city: "Manchester",
    ranking: "Russell Group",
    tuition: "£28,000 – £38,000 / year",
    programs: ["Computer Science", "Business", "Nursing", "Engineering"],
    duration: "1–3 years",
    language: "IELTS 6.5",
    visa: "Graduate Route 2 years",
  },
  {
    id: "edinburgh",
    name: "University of Edinburgh",
    country: "UK",
    city: "Edinburgh",
    ranking: "Top 15 globally",
    tuition: "£28,000 – £38,000 / year",
    programs: ["Computer Science", "Business", "Law", "Medicine"],
    duration: "1–4 years",
    language: "IELTS 6.5",
    visa: "Graduate Route 2 years",
  },
  {
    id: "uoft",
    name: "University of Toronto",
    country: "Canada",
    city: "Toronto, Ontario",
    ranking: "Top 20 globally",
    tuition: "CAD $45,000 – $55,000 / year",
    programs: ["Computer Science", "Business", "Nursing", "Engineering"],
    duration: "1–4 years",
    language: "IELTS 6.5 / TOEFL 89",
    visa: "PGWP up to 3 years",
  },
  {
    id: "ubc",
    name: "University of British Columbia",
    country: "Canada",
    city: "Vancouver, BC",
    ranking: "Top 40 globally",
    tuition: "CAD $40,000 – $50,000 / year",
    programs: ["Computer Science", "Business", "Forestry", "Engineering"],
    duration: "1–4 years",
    language: "IELTS 6.5",
    visa: "PGWP up to 3 years",
  },
  {
    id: "melbourne",
    name: "University of Melbourne",
    country: "Australia",
    city: "Melbourne",
    ranking: "Group of Eight",
    tuition: "AUD $40,000 – $50,000 / year",
    programs: ["Computer Science", "Business", "Nursing", "Law"],
    duration: "1–4 years",
    language: "IELTS 6.5",
    visa: "Post-study work 2–4 years",
  },
  {
    id: "sydney",
    name: "University of Sydney",
    country: "Australia",
    city: "Sydney",
    ranking: "Group of Eight",
    tuition: "AUD $42,000 – $52,000 / year",
    programs: ["Computer Science", "Business", "Medicine", "Engineering"],
    duration: "1–4 years",
    language: "IELTS 6.5",
    visa: "Post-study work 2–4 years",
  },
  {
    id: "tum",
    name: "Technical University of Munich",
    country: "Germany",
    city: "Munich",
    ranking: "Top technical university in Europe",
    tuition: "€0 – €3,000 / semester",
    programs: ["Computer Science", "Engineering", "Data Science"],
    duration: "2–4 years",
    language: "IELTS 6.5 / German B2 for some programs",
    visa: "18-month job seeker visa",
  },
  {
    id: "trinity",
    name: "Trinity College Dublin",
    country: "Ireland",
    city: "Dublin",
    ranking: "Ireland's #1 university",
    tuition: "€18,000 – €28,000 / year",
    programs: ["Computer Science", "Business", "Nursing"],
    duration: "1–4 years",
    language: "IELTS 6.5",
    visa: "Stay Back 1–2 years",
  },
  {
    id: "auckland",
    name: "University of Auckland",
    country: "New Zealand",
    city: "Auckland",
    ranking: "New Zealand's leading university",
    tuition: "NZD $35,000 – $45,000 / year",
    programs: ["Computer Science", "Business", "Engineering"],
    duration: "1–4 years",
    language: "IELTS 6.5",
    visa: "Post-study work 1–3 years",
  },
];

export function recommendUniversities(country: string, field: string): University[] {
  const c = country.toLowerCase();
  const f = field.toLowerCase();
  const inCountry = UNIVERSITIES.filter((u) => u.country.toLowerCase() === c);
  const pool = inCountry.length ? inCountry : UNIVERSITIES;
  const matched = pool.filter((u) =>
    u.programs.some((p) => p.toLowerCase().includes(f) || f.includes(p.toLowerCase())),
  );
  return (matched.length ? matched : pool).slice(0, 4);
}
